### ISSUE TITLE
mod making the game crash

### ISSUE THREAD

**Issue by Kysuta** [GrapeStudios/Hexalia#10]
the mod is making my game crash i play on forge 47.1.42 and i have all the reqs for it
[crash-2024-11-20_17.56.44-fml.txt](https://github.com/user-attachments/files/17834541/crash-2024-11-20_17.56.44-fml.txt)

**Comment by SirColor** [comment]
This issue has been fixed in the latest version of Hexalia. Thanks for taking the time to open up an issue.
