### ISSUE TITLE
Crashing during World Generation

### ISSUE THREAD

**Issue by SlayDigger** [GrapeStudios/Hexalia#11]
Game gets to the world creation page fine, during the creation of the world after clicking "Create World" the game crashes. 
Crash Report & Log available in this gist: []((https://gist.github.com/SlayDigger/1269c30e0ab6789524f31827ab20a06b))
Running Minecraft 1.20.1
Forge Version 47.3.12
Hexalia Version 1.0.1 (Forge)

**Comment by SirColor** [comment]
This issue has been fixed in the latest version of Hexalia, thanks a lot for pointing it out.
