### ISSUE TITLE
Crash on dedicated servers

### ISSUE THREAD

**Issue by Fealtous** [GrapeStudios/Hexalia#12]
By referencing client classes in your common setup, your mod crashes on dedicated server environments.
https://github.com/GrapeStudios/Hexalia/blob/25c41f3a21faf390bca60df08aea764c7547bfa8/src/main/java/net/grapes/hexalia/HexaliaMod.java#L74

This probably shouldn't be done in the common setup, since it's not common, it's client.

**Comment by Bersanito** [comment]
thank you! its already pending to upload :)
