### ISSUE TITLE
crash: Exception when generating new chunk

### ISSUE THREAD

**Issue by aalvscoffee** [GrapeStudios/Hexalia#8]
1.20.1 Forge - I found a bug when new chunks are generated when hexalia is in conjunction with some world generation modifications by other mods

here are 2 examples, 1 with the mod terralith & 1 without it (i dont know what is causing it here)

without terralith [https://mclo.gs/JmOgTBr](url) with terralith [https://mclo.gs/zvP2Qzr](url)

**Comment by SirColor** [comment]
Hello, would you be so kind to share the crash files again? The links does not seem to work.

**Comment by aalvscoffee** [comment]
sure!
https://mclo.gs/JmOgTBr
https://mclo.gs/zvP2Qzr

**Comment by SirColor** [comment]
The crash comes with the issue stems from how features are added in TerraBlender, for now, a _temporary_ solution is installing Feature Recycler (https://www.curseforge.com/minecraft/mc-mods/feature-recycler) until we fix this issue. Sorry for the inconveniences, and thanks for trying out the mod.
